# Logistic Regression Implementation

In [144]:
from sklearn.datasets import load_iris
import pandas as pd

# iris is a flower related dataset

In [145]:
dataset=load_iris() 

#  dataset here is the object returned by load_iris(), and it acts like a dictionary with attributes.

In [146]:
print(dataset.DESCR)

# dataset.DESCR gives you the dataset’s built-in description text (a long human-readable summary)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [147]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [148]:
dataset.target
# type(dataset.target) # this is an ndArray so we will trans

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [149]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [150]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2


In [151]:
df['target']=dataset.target

In [152]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [153]:
df.shape

(150, 5)

In [ ]:
# confusion matrix : 

# For a binary classifier, after predicting on test data you get 4 outcomes:

#                         Predicted: Positive         Predicted: Negative

# Actual: Positive        TP (True Positive)          FN (False Negative)
# Actual: Negative        FP (False Positive)         TN (True Negative)

# TP — You said positive, it was positive. Correct.
# TN — You said negative, it was negative. Correct.
# FP — You said positive, actually negative. Type I error.
# FN — You said negative, actually positive. Type II error.

# The matrix tells you where your model fails, not just whether it fails.

# Ex - [[12  0]
#       [ 0  8]]

# it means : 

# 12 → Model predicted class 0, actual was class 0. Correct.
# 8 → Model predicted class 1, actual was class 1. Correct.
# 0 (top right) → Model predicted class 1, actual was class 0. Wrong. → Zero such mistakes.
# 0 (bottom left) → Model predicted class 0, actual was class 1. Wrong. → Zero such mistakes.

In [154]:
# Binary classification

# df[df['target']==2] # therefore these exists

df_copy=df[df['target']!=2] # we can do this to make the classification binary

df_copy.shape

(100, 5)

In [155]:
df_copy.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


# Independent and dependent features

In [156]:
X=df_copy.iloc[:,:-1] # everything except target column
y=df_copy.iloc[:,-1] # only last column

In [157]:
from sklearn.linear_model import LogisticRegression

In [158]:
classifier=LogisticRegression()

In [159]:
# train-test split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=20,random_state=42)

In [160]:
classifier.fit(X_train,y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [161]:
# prediction
y_pred=classifier.predict(X_test)

In [162]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [163]:
y_test

83    1
53    1
70    1
45    0
44    0
39    0
22    0
80    1
10    0
0     0
18    0
30    0
73    1
33    0
90    1
4     0
76    1
77    1
12    0
31    0
Name: target, dtype: int64

In [ ]:
# Accuracy, confusion matrix, and classification report
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Always pass y_true first and y_pred second
print('Accuracy:', accuracy_score(y_test, y_pred))
print('\nConfusion Matrix:\n', confusion_matrix(y_test, y_pred))
print('\nClassification Report:\n', classification_report(y_test, y_pred))

1.0
[[12  0]
 [ 0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## Additional Concepts You Should Know (Logistic Regression)

These are important topics often asked in interviews and useful in real projects:

1. Sigmoid function and probability output
2. Decision threshold (not always 0.5)
3. Coefficients, odds, and log-odds interpretation
4. Regularization (`L1`, `L2`, and `C`)
5. ROC-AUC and threshold tuning
6. Important assumptions and practical tips

### 1. Sigmoid Function and Why Logistic Regression Gives Probabilities

Logistic Regression predicts a linear score:

$$
z = w_1x_1 + w_2x_2 + ... + b
$$

Then converts it to probability using sigmoid:

$$
\sigma(z)=\frac{1}{1+e^{-z}}
$$

- Output is always between 0 and 1
- This value is the probability of class 1 (positive class)

In [ ]:
# Plot sigmoid curve for intuition
import numpy as np
import matplotlib.pyplot as plt

z = np.linspace(-10, 10, 200)
sigmoid = 1 / (1 + np.exp(-z))

plt.figure(figsize=(8, 4))
plt.plot(z, sigmoid)
plt.axhline(0.5, color='red', linestyle='--', label='0.5 probability')
plt.title('Sigmoid Function')
plt.xlabel('z (linear score)')
plt.ylabel('Probability')
plt.legend()
plt.grid(alpha=0.3)
plt.show()

### 2. Decision Threshold (Very Important)

By default, prediction rule is:
- if probability >= 0.5, predict class 1
- else predict class 0

But threshold can be changed based on business goal:
- Lower threshold: catches more positives, but may increase false positives
- Higher threshold: fewer false positives, but may miss true positives

So 0.5 is not always the best choice.

In [ ]:
# Try different thresholds and observe confusion matrix changes
from sklearn.metrics import confusion_matrix

proba_class1 = classifier.predict_proba(X_test)[:, 1]

for threshold in [0.3, 0.5, 0.7]:
    y_pred_threshold = (proba_class1 >= threshold).astype(int)
    cm = confusion_matrix(y_test, y_pred_threshold)
    acc = accuracy_score(y_test, y_pred_threshold)
    print(f'\nThreshold = {threshold}')
    print('Accuracy:', round(acc, 4))
    print('Confusion Matrix:\n', cm)

### 3. Coefficients, Log-Odds, and Odds Ratio

Logistic regression models **log-odds**:

$$
\log\left(\frac{p}{1-p}\right)=w_1x_1 + w_2x_2 + ... + b
$$

- A positive coefficient increases probability of class 1
- A negative coefficient decreases probability of class 1
- `exp(coefficient)` gives the **odds ratio** for a 1-unit increase in that feature

In [ ]:
# Coefficient interpretation table
coef_values = classifier.coef_[0]  # binary classification gives one coefficient vector
coef_table = pd.DataFrame({
    'feature': X.columns,
    'coefficient': coef_values,
    'odds_ratio_exp_coef': np.exp(coef_values)
}).sort_values('coefficient', ascending=False)

coef_table

### 4. Regularization (`L1`, `L2`) and `C`

Regularization helps prevent overfitting.

- `L2` (Ridge-like): shrinks coefficients smoothly
- `L1` (Lasso-like): can push some coefficients to zero (feature selection effect)
- `C` is inverse of regularization strength:
  - smaller `C` => stronger regularization
  - larger `C` => weaker regularization

In [ ]:
# Compare regularization settings
from sklearn.linear_model import LogisticRegression

settings = [
    ('l2', 0.1),
    ('l2', 1.0),
    ('l2', 10.0),
    ('l1', 0.1),
    ('l1', 1.0),
    ('l1', 10.0),
]

rows = []
for penalty, C in settings:
    model_temp = LogisticRegression(penalty=penalty, C=C, solver='liblinear', random_state=42)
    model_temp.fit(X_train, y_train)
    pred_temp = model_temp.predict(X_test)
    rows.append({
        'penalty': penalty,
        'C': C,
        'test_accuracy': accuracy_score(y_test, pred_temp)
    })

pd.DataFrame(rows).sort_values('test_accuracy', ascending=False)

### 5. ROC Curve and AUC

ROC-AUC evaluates ranking quality of predicted probabilities across all thresholds.

- ROC curve: True Positive Rate vs False Positive Rate
- AUC close to 1: strong separability
- AUC around 0.5: near-random model

This is useful when accuracy alone is not enough.

In [ ]:
# ROC curve and AUC score
from sklearn.metrics import roc_curve, roc_auc_score

fpr, tpr, _ = roc_curve(y_test, proba_class1)
auc_score = roc_auc_score(y_test, proba_class1)

plt.figure(figsize=(6, 5))
plt.plot(fpr, tpr, label=f'ROC curve (AUC = {auc_score:.3f})')
plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Random baseline')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.grid(alpha=0.3)
plt.show()

### 6. Assumptions and Practical Tips

Logistic Regression works best when:
- Relationship between features and log-odds is approximately linear
- Features are scaled (important for regularized logistic regression)
- Severe multicollinearity is avoided
- Outliers are handled

Practical notes:
- For imbalanced data, monitor precision/recall/F1, not only accuracy
- Use `class_weight='balanced'` when class imbalance is high
- Tune threshold based on business cost of FP vs FN
- Use cross-validation for robust model selection

## Quick Recap

You now understand:
- Why logistic regression outputs probabilities (sigmoid)
- Why threshold tuning is important
- How to interpret coefficients and odds ratios
- How regularization controls overfitting
- Why ROC-AUC is useful beyond accuracy
- Key assumptions and real-world tips