## Numpy array and basics

In [16]:
import numpy as np
# numpy is a very optimised library used to perform operations on homogenous datatypes which take more time in traditional way

### creating array from list

In [17]:
arr_1d=np.array([1,2,3,4,5]) # array only needs a single argument
print("1D array : ",arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]]) # array only needs a single argument that's why we enclosed the two lists in a single bracket
print("2D array : \n",arr_2d)

1D array :  [1 2 3 4 5]
2D array : 
 [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [18]:
py_list=[1,2,3]
print("Python list multiplication : ",py_list*2) # list will be duplicated

np_arr=np.array([1,2,3])
print("Numpy array multiplication : ",np_arr*2) # actual array multiplication (element wise multiplication)

Python list multiplication :  [1, 2, 3, 1, 2, 3]
Numpy array multiplication :  [2 4 6]


### creating arrays from scratch

In [ ]:
zeros=np.zeros((3,4)) # 3,4 is the dimension
print("Zeros array : \n",zeros)

ones=np.ones((2,3)) # 2,3 is the dimension
print("Ones array : \n",ones)

# array of constant values

full=np.full((2,2), 7) # here 7 is the constant and 2,2 is the dimension
print("constant array : \n",full)

# random method

random=np.random.random((2,3)) # random is a class and random.random is a method of that random class which return an array of random values of given dimensions
print("random array : \n",random)

# arange

sequence=np.arange(0,10,2) # start , stop(non-inclusive bound) , step
print("The array is : ",sequence)

Zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]]
constant array : 
 [[7 7]
 [7 7]]
random array : 
 [[0.72697622 0.54329573 0.54045255]
 [0.91550435 0.5013608  0.90816738]]
The array is :  [0 2 4 6 8]


### vector , matrix , tensor

In [ ]:
# Vector

vector=np.array([1,2,3])
print("Vector : ",vector)

# Matrix (2-D array)

matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Matrix : \n",matrix)

# Tensor (multidimensional array)

tensor=np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]],
                [[13,14,15],[16,17,18]]])
print("Tensor : \n",tensor)

Vector :  [1 2 3]
Matrix : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor : 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


### Array properties

In [14]:
arr=np.array([[1,2,3],
              [4,5,6]])
print("Shape : ",arr.shape) # gives rows and columns
print("Dimension : ",arr.ndim) # gives dimension of array
print("Size : ",arr.size) # total number of elements
print("Datatype : ",arr.dtype) # gives datatype of array

Shape :  (2, 3)
Dimension :  2
Size :  6
Datatype :  int64


### Array reshaping

In [21]:
arr=np.arange(12)
print("Original array : ",arr)

# reshape

reshaped=arr.reshape((3,4)) # converting it to the matrix of size 3,4 . Note - the reshaped matrix should have same number of elements as before
print("Reshaped array : \n",reshaped)

# flatten (it doesn't changes the original array)

flattened=reshaped.flatten()
print("Flattened array : ",flattened)

# ravel (returns view , instead of copy i.e. it changes the original array)

raveled=flattened.ravel()
print("Raveled array : ",raveled)

# transpose (T)

transposed=reshaped.T
print("Transposed array : \n",transposed)

Original array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
